[package]
name = "guid"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc={path="../../linux/libc"}
drm={path="../../linux/drm"}
gbm={path="../../linux/gbm"}
egl={path="../../linux/egl"}
drawing={path="../drawing"}
gles={path="../../linux/openGL/gles"}